### ISSUE TITLE
Support for vec lenghts parameter declared with proc

### ISSUE THREAD

**Issue by VitorEAFeliciano** [Terraspace/UASM#101]
With my tests and getting to know uasm code, still if using some vec convention with proc the reference for the vec oword or __m128 gets translated to rsp+index parameter.

example:
	.x64
	option casemap:none
	option win64:15
	option frame:auto
	option STACKBASE:RSP

public VECTORCALL uX_mm_move_ps

uX_mm_move_ps PROTO VECTORCALL (xmmword) Inxmm_A:xmmword

uX_mm_move_ps PROC VECTORCALL (xmmword) Inxmm_A:xmmword
	movaps   xmm0,   Inxmm_A
	ret
uX_mm_move_ps ENDP

Gets this assembled:
; uX_mm_move_ps(x, x, x, x)
public uX_mm_move_ps@@16
uX_mm_move_ps@@16 proc near

arg_0= xmmword ptr  8

movaps  xmm0, [rsp+arg_0]
retn
uX_mm_move_ps@@16 endp

The idea:

if (proc->sym.langtype == LANG_VECTORCALL)
if ((paranode->sym.mem_type == MT_REAL4) || (paranode->sym.mem_type == MT_REAL8) || (paranode->sym.mem_type == MT_TYPE && _stricmp(paranode->sym.type->name, "__m128") == 0) || paranode->sym.mem_type == MT_OWORD)
if (((GetValueSp(reg) & OP_XMM) & reg < T_XMM6)
AddLineQueueX("movaps %r, %s", ms64_regsXMM[index], paramtoreg(paramlist));

To gets this assembled for vector convention:
; uX_mm_move_ps(x, x, x, x)
public uX_mm_move_ps@@16
uX_mm_move_ps@@16 proc near
movaps  xmm0, xmm0
retn
uX_mm_move_ps@@16 endp

**Comment by john-terraspace** [comment]
This should work in a similar fashion to the sysv proc handler, it uses the register names in place of the argument name.

**Comment by VitorEAFeliciano** [comment]
OK, its working now.

If i don't declare procedure as manual frame, the stack is never used.

This
`
    option casemap:none
    .X64P
    option win64:15             ; 11-15 for RSP and 1-7 for RBP.
    option frame:auto
    option stackbase:rsp        ; RSP or RBP are supported options for the stackbase.

    .xmm
    option arch:sse
    option evex:0
    
    .data?

    .data
    
    .const

    .code
    
    callconvopt
    alignxmmfieldproc

funcstart _uX_mm_move_ps, callconv, xmmword, < >, < >, Inxmm_A:xmmword
            movaps          xmm0,       xmm0
            ret
funcend

    end
`

Produce this:
`
.686p
.mmx
.model flat

; Segment type: Pure code
; Segment permissions: Read/Execute
_text segment para public 'CODE' use64
assume cs:_text
assume es:nothing, ss:nothing, ds:_data, fs:nothing, gs:nothing

; uX_mm_move_ps(x, x, x, x)
public _uX_mm_move_ps@@16
_uX_mm_move_ps@@16 proc near
movaps  xmm0, xmm0
retn
_uX_mm_move_ps@@16 endp
`
