### ISSUE TITLE
General failure in empty object without '-win64'

### ISSUE THREAD

**Issue by vid512** [Terraspace/UASM#102]
Following code produces General failure error:

> .x64
> option win64:7
> .code
> nop
> end

Why? Is it a bug, or is there something missing? At least more detailed error message would be welcome.

**Comment by vid512** [comment]
Note: This happens when compiled without '-win64' command line option.

**Comment by VitorEAFeliciano** [comment]
That means the UASM cant find the platform specified.

command-line:
  Windows for:
    32bits= -coff
    64bits= -win64

  Linux for:
    32bits= -elf
    64bits= -elf64

  Linux for:
   hallways 64bits:-macho64

**Comment by john-terraspace** [comment]
It shouldn’t gen. fail. 

Will fix.

**Comment by VitorEAFeliciano** [comment]
option win64:7 is also implemented for linux64 stack & conventions, so calling option win64:7 aren't en-off to produce the object

**Comment by john-terraspace** [comment]
Fixed general failure in latest version. Will be included in 2.49 release.
