### ISSUE TITLE
Default PROC prologue requires FRAME set

### ISSUE THREAD

**Issue by vid512** [Terraspace/UASM#103]
I want to generate an object file with simple procedure, without any unwind data. However the current default PROC prologue seems to require the "FRAME" to be set.

Example code (compile with just '-win64'):
> option stackbase:rsp
> option frame:noauto
> .code
> xyz PROC arg1:dword, arg2:ptr char
> ret
> xyz ENDP
> end

This causes error A2258 "Missing FRAME in PROC, no unwind code will be generated".

Shouldn't that be the point of OPTION FRAME:NOAUTO, not to generate the unwind code unless explicitly requested?

**Comment by mazegen** [comment]
Try this:
```
option stackbase:rsp
option frame:noauto
.code
xyz PROC FRAME arg1:dword, arg2:ptr char
mov eax,arg1
mov rbx,arg2
ret
xyz ENDP
end
```

**Comment by vid512** [comment]
That compiles, but the unwind data is still generated (as expected). I want to only generate the procedure without any unwind data.

**Comment by VitorEAFeliciano** [comment]
option frame:noauto, disables smart frame uses for rsp proc requeriments implemented by habran, 

noauto means 

manualy frames with rsp are required hallways.

check manual [http://www.terraspace.co.uk/uasm248_ext.pdf](url)
