### ISSUE TITLE
Here are some assembly Bugs found during my work

### ISSUE THREAD

**Issue by willi-neu9** [Terraspace/UASM#108]
Hi UASM Folks

UASM is really a great tool to replace MASM on Visual Studio Environment.

But I found some assembly Bugs (things that not assembled as exspected)

See attached Sources and belonging .lst file. Maybe you can fix this.

**Comment by willi-neu9** [comment]
[AssemblyBugs.zip](https://github.com/Terraspace/UASM/files/3364178/AssemblyBugs.zip)
Hi UASM Folks,

Here is the Source File and belonging .lst file that displays some assembly issues found during my work. Maybe you can fix them.

**Comment by john-terraspace** [comment]
Have you tried this with 2.49 ?

I  tested the mov sizing related issue and the assembled output is:
167:    c6 01 7f                mov    BYTE PTR [ecx],0x7f
16a:    c6 01 80                mov    BYTE PTR [ecx],0x80
16d:    80 21 7f                and    BYTE PTR [ecx],0x7f
170:    80 21 80                and    BYTE PTR [ecx],0x80
173:    80 09 7f                or     BYTE PTR [ecx],0x7f
176:    80 09 80                or     BYTE PTR [ecx],0x80

Which is correct. Please re-check and let me know.
I am looking into the EQU issue.

**Comment by willi-neu9** [comment]
Hi John,

You are right, the assembly bug is not in the uasm64.exe Version taken from "http://www.terraspace.co.uk/uasm.html" today,

But for removing the .lst bug I've recompiled the Version 2.49 found on github on May,15,2019 (https://github.com/Terraspace/UASM) with Visual Studio 2019.

And with this recompiled Version of May,15th,2019 the following bug exist:

00000106  C6017F                            mov    byte ptr [ecx],7fh     ; correctly assembled to 'byte ptr [ecx],7fh'
00000109  C70180000000                      mov    byte ptr [ecx],80h     ; wrongly assembled to 'dword ptr [ecx],00000080h'

Buf fixed in the newer Version on github.

Best regards

/Will/

**Comment by john-terraspace** [comment]
Just to add some clarity to the other issue:

 

After a lot of testing,

 

SymFind("Lenx")

0x000001a3308aaab8 {nextitem=0x0000000000000000 <NULL> name=0x000001a3308aab50 "Lenx" string_ptr=0x0000000000000000 <NULL> ...}

    nextitem: 0x0000000000000000 <NULL>

    name: 0x000001a3308aab50 "Lenx"

    string_ptr: 0x0000000000000000 <NULL>

    offset: 0x00000006

    value: 0x00000006

    uvalue: 0x00000006

 

By the time we each the 3rd pass the value is correct for Len0/1/2 and Lenx.

It requires multiple passes to resolve as the size of the cmp opcode changes from 3 to 6 bytes as the value stabilises.

 

So if you were to use the EQU in code, it is correct. The problem appears to be that the text equate is evaluated once in the first pass/2nd pass so it shows at 3 instead of 6.

**Comment by willi-neu9** [comment]
Hi John,

the problem is not the TEXT equ. What mostely is a problem that an IF statement is also
assambled incorrectly (see attached example).

There you can see that the 2nd IF statement "if (Lenx2 eq 3)" is also equated as
TRUE even though Lenx2 has a value of 6.

Best regards


/Willi/

  ----- Original Message -----

**Comment by willi-neu9** [comment]
Hi John,

that the TEXT equ is not assemlbed correctly is not a main problem. But also IF statments are also not
correctly assembled (see attached example).

If you look at line 27 you see that Lenx2 is calculated as 6 but the corresponding IF statement
"if (Lenx2 eq 3)"  on line 35 is wrongly equated as TRUE.

Best regards


/Willi/
  ----- Original Message -----

**Comment by john-terraspace** [comment]
Hi,

 

I’ve gotten to the root of the problem and have a simple test-case now. I’ve tried it with MASM and that seems to produce the same output.

Could you please double check / confirm that you have the same error in MASM.

 

Basically the issue comes down to the fact that pre-processing (IF/ELSE etc) is handled by both assemblers in the 1st pass.. so when an equate size changes per pass the outcome isn’t correctly handled.

 

Let me know how that goes.

**Comment by willi-neu9** [comment]
Hi John,

one of the main reasons why I use UASM instead of MASM is that MASM has so many bugs
that I cannot work with it.

OK what MASM does is that everytime a forward reference of symbols is found in an equation
as shown in my example it always selects the DWORD version of the instruction, instead of
assembling the short one if possible. That is really a bonus point for UASM.

The next is in MASM if there is a forward reference in symbols and this is calculated as 6 the
correspondig IF statement is only TRUE if compared against 14.

Really very buggy!

So if you cannot resolve this IF compare problem with forward references just leave it as it is.

I've found the following workaround.

        db  (6-Lenx1) dup (90h)
        db  (6-Lenx2) dup (90h)

This also generates fill nops if the above compare is assembled as short instruction.

Best regards



/Willi/

  ----- Original Message -----

**Comment by john-terraspace** [comment]
I think we can fix it, but it’s quite a fundamental change to how the pass evaluations are handled. It may not be in the next release, but it should be on the back-log as it’s fundamentally flawed. Any change to a value should cause the subsequent pass to re-evaluate anything that is dependant on the item that has changed.

 

Agreed on Masm.. and as for 64bit it’s almost a no go anymore!

 

John
