### ISSUE TITLE
Invalid Line Delimiter in .lst file

### ISSUE THREAD

**Issue by willi-neu9** [Terraspace/UASM#109]
[uasm-list-Bug.zip](https://github.com/Terraspace/UASM/files/3365448/uasm-list-Bug.zip)

Hi Folks,

Some Windows Editor complains a wrong line Delimiter in created .LST file. The listing startup:
"UASM v" _UASM_VERSION_ ", " __DATE__ ", Masm-compatible assembler.\n" has a line feed without preceding '\r' (CR).

Here is a example that fixes the wrong output of above described listing startup line.
In UASM source file "listing.c" in function "LstInit" I changed the following lines:

void LstInit( void )
/******************/
{
    const struct fname_item *fn;
    const char *buffer;

    list_pos = 0;
    if( Options.write_listing ) {
        int namelen;
        buffer = MsgGetEx( MSG_UASM );
        list_pos = strlen( buffer ) - 1;                // -1 by willi
        fwrite( buffer, 1, list_pos, CurrFile[LST] );
		LstNL();
		LstNL();                                // Added by willi
		fn = GetFName( ModuleInfo.srcfile );
        namelen = strlen( fn->fname );
        fwrite( fn->fname, 1, namelen, CurrFile[LST] );
        list_pos += namelen;
        LstNL();
    }
}

Maybe you can fix that (small) bug in the next release.

Best regards

/Willi/

**Comment by john-terraspace** [comment]
Done in 2.50
