### ISSUE TITLE
doesn't build on linux with conflicting types

### ISSUE THREAD

**Issue by alexge233** [Terraspace/UASM#112]
Hi, I'm trying to build on Linux amd64 and I get two different compilation errors:

```
codegenv2.c:1170:5: error: conflicting types for ‘BuildMemoryEncoding’
 int BuildMemoryEncoding(unsigned char* pmodRM, unsigned char* pSIB, unsigned char* pREX, bool* needModRM, bool* needSIB,
     ^~~~~~~~~~~~~~~~~~~
In file included from codegenv2.c:5:0:
H/codegenv2.h:391:15: note: previous declaration of ‘BuildMemoryEncoding’ was here
 int           BuildMemoryEncoding(unsigned char* pmodRM, unsigned char* pSIB, unsigned char* pREX, bool* needRM, bool* need
```

and

```
codegenv2.c:1655:15: error: too many arguments to function ‘BuildREX’
    rexByte |= BuildREX(rexByte, matchedInstr, opExpr, FALSE);           /* Modify the REX prefix for non-memory operands/sizing */
```

This is using master branch.

**Comment by john-terraspace** [comment]
Try the 2.49.1 branch, I’m still in the process of cleaning up and updating master. I had no issues building 2.49 on Linux.

**Comment by alexge233** [comment]
Hi @john-terraspace I've just tried, also tried the final one, seem to be getting a different error of multiple definitions on linking:

```
gcc -D __UNIX__ GccUnixR/main.o GccUnixR/apiemu.o GccUnixR/orgfixup.o GccUnixR/assemble.o GccUnixR/assume.o GccUnixR/atofloat.o GccUnixR/backptch.o GccUnixR/bin.o GccUnixR/branch.o GccUnixR/cmdline.o GccUnixR/codegen.o GccUnixR/codegenv2.o GccUnixR/coff.o GccUnixR/condasm.o GccUnixR/context.o GccUnixR/cpumodel.o GccUnixR/data.o GccUnixR/dbgcv.o GccUnixR/directiv.o GccUnixR/elf.o GccUnixR/end.o GccUnixR/equate.o GccUnixR/errmsg.o GccUnixR/expans.o GccUnixR/expreval.o GccUnixR/extern.o GccUnixR/fastpass.o GccUnixR/fixup.o GccUnixR/fpfixup.o GccUnixR/hll.o GccUnixR/input.o GccUnixR/invoke.o GccUnixR/label.o GccUnixR/linnum.o GccUnixR/listing.o GccUnixR/loop.o GccUnixR/lqueue.o GccUnixR/ltype.o GccUnixR/macho64.o GccUnixR/macro.o GccUnixR/macrolib.o GccUnixR/mangle.o GccUnixR/memalloc.o GccUnixR/msgtext.o GccUnixR/omf.o GccUnixR/omffixup.o GccUnixR/omfint.o GccUnixR/option.o GccUnixR/parser.o GccUnixR/posndir.o GccUnixR/preproc.o GccUnixR/proc.o GccUnixR/queue.o GccUnixR/reswords.o GccUnixR/safeseh.o GccUnixR/segment.o GccUnixR/simd.o GccUnixR/simsegm.o GccUnixR/string.o GccUnixR/symbols.o GccUnixR/tbyte.o GccUnixR/pseudoFilter.o GccUnixR/tokenize.o GccUnixR/types.o -s -o GccUnixR/uasm -Wl,-Map,GccUnixR/uasm.map
GccUnixR/coff.o:(.bss+0x0): multiple definition of `MODULEARCH'
GccUnixR/main.o:(.bss+0x0): first defined here
GccUnixR/condasm.o:(.bss+0x0): multiple definition of `MODULEARCH'
GccUnixR/main.o:(.bss+0x0): first defined here
GccUnixR/context.o:(.bss+0x0): multiple definition of `MODULEARCH'
GccUnixR/main.o:(.bss+0x0): first defined here
GccUnixR/cpumodel.o:(.bss+0x0): multiple definition of `MODULEARCH'
GccUnixR/main.o:(.bss+0x0): first defined here
GccUnixR/dbgcv.o:(.bss+0x0): multiple definition of `MODULEARCH'
GccUnixR/main.o:(.bss+0x0): first defined here
GccUnixR/directiv.o:(.bss+0x0): multiple definition of `MODULEARCH'
GccUnixR/main.o:(.bss+0x0): first defined here
GccUnixR/elf.o:(.bss+0x0): multiple definition of `MODULEARCH'
GccUnixR/main.o:(.bss+0x0): first defined here
GccUnixR/end.o:(.bss+0x0): multiple definition of `MODULEARCH'
GccUnixR/main.o:(.bss+0x0): first defined here
GccUnixR/equate.o:(.bss+0x0): multiple definition of `MODULEARCH'
GccUnixR/main.o:(.bss+0x0): first defined here
GccUnixR/errmsg.o:(.bss+0x1): multiple definition of `MODULEARCH'
GccUnixR/main.o:(.bss+0x0): first defined here
GccUnixR/expans.o:(.bss+0x0): multiple definition of `MODULEARCH'
GccUnixR/main.o:(.bss+0x0): first defined here
GccUnixR/extern.o:(.bss+0x0): multiple definition of `MODULEARCH'
GccUnixR/main.o:(.bss+0x0): first defined here
GccUnixR/fastpass.o:(.bss+0x0): multiple definition of `MODULEARCH'
GccUnixR/main.o:(.bss+0x0): first defined here
GccUnixR/fixup.o:(.bss+0x0): multiple definition of `MODULEARCH'
GccUnixR/main.o:(.bss+0x0): first defined here
GccUnixR/fpfixup.o:(.bss+0x0): multiple definition of `MODULEARCH'
GccUnixR/main.o:(.bss+0x0): first defined here
GccUnixR/hll.o:(.bss+0x0): multiple definition of `MODULEARCH'
GccUnixR/main.o:(.bss+0x0): first defined here
GccUnixR/input.o:(.bss+0x0): multiple definition of `MODULEARCH'
GccUnixR/main.o:(.bss+0x0): first defined here
GccUnixR/label.o:(.bss+0x0): multiple definition of `MODULEARCH'
GccUnixR/main.o:(.bss+0x0): first defined here
GccUnixR/linnum.o:(.bss+0x0): multiple definition of `MODULEARCH'
GccUnixR/main.o:(.bss+0x0): first defined here
GccUnixR/listing.o:(.bss+0x0): multiple definition of `MODULEARCH'
GccUnixR/main.o:(.bss+0x0): first defined here
GccUnixR/loop.o:(.bss+0x0): multiple definition of `MODULEARCH'
GccUnixR/main.o:(.bss+0x0): first defined here
GccUnixR/lqueue.o:(.bss+0x0): multiple definition of `MODULEARCH'
GccUnixR/main.o:(.bss+0x0): first defined here
GccUnixR/ltype.o:(.bss+0x0): multiple definition of `MODULEARCH'
GccUnixR/main.o:(.bss+0x0): first defined here
GccUnixR/macho64.o:(.bss+0x0): multiple definition of `MODULEARCH'
GccUnixR/main.o:(.bss+0x0): first defined here
GccUnixR/macro.o:(.bss+0x1): multiple definition of `MODULEARCH'
GccUnixR/main.o:(.bss+0x0): first defined here
GccUnixR/mangle.o:(.bss+0x0): multiple definition of `MODULEARCH'
GccUnixR/main.o:(.bss+0x0): first defined here
GccUnixR/memalloc.o:(.bss+0x0): multiple definition of `MODULEARCH'
GccUnixR/main.o:(.bss+0x0): first defined here
GccUnixR/omf.o:(.bss+0x0): multiple definition of `MODULEARCH'
GccUnixR/main.o:(.bss+0x0): first defined here
GccUnixR/omffixup.o:(.bss+0x0): multiple definition of `MODULEARCH'
GccUnixR/main.o:(.bss+0x0): first defined here
GccUnixR/omfint.o:(.bss+0x0): multiple definition of `MODULEARCH'
GccUnixR/main.o:(.bss+0x0): first defined here
GccUnixR/posndir.o:(.bss+0x0): multiple definition of `MODULEARCH'
GccUnixR/main.o:(.bss+0x0): first defined here
GccUnixR/reswords.o:(.bss+0x0): multiple definition of `MODULEARCH'
GccUnixR/main.o:(.bss+0x0): first defined here
GccUnixR/safeseh.o:(.bss+0x0): multiple definition of `MODULEARCH'
GccUnixR/main.o:(.bss+0x0): first defined here
GccUnixR/segment.o:(.bss+0x0): multiple definition of `MODULEARCH'
GccUnixR/main.o:(.bss+0x0): first defined here
GccUnixR/simd.o:(.bss+0x0): multiple definition of `MODULEARCH'
GccUnixR/main.o:(.bss+0x0): first defined here
GccUnixR/string.o:(.bss+0x0): multiple definition of `MODULEARCH'
GccUnixR/main.o:(.bss+0x0): first defined here
GccUnixR/symbols.o:(.bss+0x0): multiple definition of `MODULEARCH'
GccUnixR/main.o:(.bss+0x0): first defined here
GccUnixR/tbyte.o:(.bss+0x0): multiple definition of `MODULEARCH'
GccUnixR/main.o:(.bss+0x0): first defined here
GccUnixR/types.o:(.bss+0x0): multiple definition of `MODULEARCH'
GccUnixR/main.o:(.bss+0x0): first defined here
collect2: error: ld returned 1 exit status
GccUnix.mak:43: recipe for target 'GccUnixR/uasm' failed
make: *** [GccUnixR/uasm] Error 1

```

**Comment by john-terraspace** [comment]
Here is the makefile I use on Linux (Ubuntu 18 64bit)…

 

 

# This makefile creates the Uasm Elf binary for Linux/FreeBSD.

 

TARGET1=uasm

 

ifndef DEBUG

DEBUG=0

endif

 

inc_dirs  = -IH

 

#cflags stuff

 

ifeq ($(DEBUG),0)

extra_c_flags = -DNDEBUG -O2 -funsigned-char -Wwrite-strings

OUTD=GccUnixR

else

extra_c_flags = -DDEBUG_OUT -g

OUTD=GccUnixD

endif

 

c_flags =-D __UNIX__ $(extra_c_flags)

 

CC = gcc

 

.SUFFIXES:

.SUFFIXES: .c .o

 

include gccmod.inc

 

#.c.o:

#             $(CC) -c $(inc_dirs) $(c_flags) -o $(OUTD)/$*.o $<

$(OUTD)/%.o: %.c

                $(CC) -D __UNIX__ -c $(inc_dirs) $(c_flags) -o $(OUTD)/$*.o $<

 

all:  $(OUTD) $(OUTD)/$(TARGET1)

 

$(OUTD):

                mkdir $(OUTD)

 

$(OUTD)/$(TARGET1) : $(OUTD)/main.o $(proj_obj)

ifeq ($(DEBUG),0)

                $(CC) -D __UNIX__ $(OUTD)/main.o $(proj_obj) -s -o $@ -Wl,-Map,$(OUTD)/$(TARGET1).map

else

                $(CC) -D __UNIX__ $(OUTD)/main.o $(proj_obj) -o $@ -Wl,-Map,$(OUTD)/$(TARGET1).map

endif

 

$(OUTD)/msgtext.o: msgtext.c H/msgdef.h

                $(CC) -D __UNIX__ -c $(inc_dirs) $(c_flags) -o $*.o msgtext.c

 

$(OUTD)/reswords.o: reswords.c H/instruct.h H/special.h H/directve.h H/opndcls.h H/instravx.h

                $(CC) -D __UNIX__ -c $(inc_dirs) $(c_flags) -o $*.o reswords.c

 

######

 

clean:

                rm $(OUTD)/$(TARGET1)

                rm $(OUTD)/*.o

                rm $(OUTD)/*.map

 

 

That builds without issue for me.

I’m using:

 

gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0

Copyright (C) 2017 Free Software Foundation, Inc.

 

Gccmod.inc as follows:

 

proj_obj = \

$(OUTD)/apiemu.o   \

$(OUTD)/orgfixup.o \

$(OUTD)/assemble.o \

$(OUTD)/assume.o   \

$(OUTD)/atofloat.o \

$(OUTD)/backptch.o \

$(OUTD)/bin.o      \

$(OUTD)/branch.o   \

$(OUTD)/cmdline.o  \

$(OUTD)/codegen.o  \

$(OUTD)/codegenv2.o  \

$(OUTD)/coff.o     \

$(OUTD)/condasm.o  \

$(OUTD)/context.o  \

$(OUTD)/cpumodel.o \

$(OUTD)/data.o     \

$(OUTD)/dbgcv.o    \

$(OUTD)/directiv.o \

$(OUTD)/elf.o      \

$(OUTD)/end.o      \

$(OUTD)/equate.o   \

$(OUTD)/errmsg.o   \

$(OUTD)/expans.o   \

$(OUTD)/expreval.o \

$(OUTD)/extern.o   \

$(OUTD)/fastpass.o \

$(OUTD)/fixup.o    \

$(OUTD)/fpfixup.o  \

$(OUTD)/hll.o      \

$(OUTD)/input.o    \

$(OUTD)/invoke.o   \

$(OUTD)/label.o    \

$(OUTD)/linnum.o   \

$(OUTD)/listing.o  \

$(OUTD)/loop.o     \

$(OUTD)/lqueue.o   \

$(OUTD)/ltype.o    \

$(OUTD)/macho64.o  \

$(OUTD)/macro.o    \

$(OUTD)/macrolib.o \

$(OUTD)/mangle.o   \

$(OUTD)/memalloc.o \

$(OUTD)/msgtext.o  \

$(OUTD)/omf.o      \

$(OUTD)/omffixup.o \

$(OUTD)/omfint.o   \

$(OUTD)/option.o   \

$(OUTD)/parser.o   \

$(OUTD)/posndir.o  \

$(OUTD)/preproc.o  \

$(OUTD)/proc.o     \

$(OUTD)/queue.o    \

$(OUTD)/reswords.o \

$(OUTD)/safeseh.o  \

$(OUTD)/segment.o  \

$(OUTD)/simd.o     \

$(OUTD)/simsegm.o  \

$(OUTD)/string.o   \

$(OUTD)/symbols.o  \

$(OUTD)/tbyte.o    \

$(OUTD)/pseudoFilter.o \

$(OUTD)/tokenize.o \

$(OUTD)/types.o

**Comment by alexge233** [comment]
Hi @john-terraspace is this the same as the `GccUnix.mak` makefile?
Could you please format it, it has illegal characters in it atm?

**Comment by john-terraspace** [comment]
I’ve updated the 2.50 branch with new makefiles. GccLinux64.mak + gccmod.inc are as I use. Try that.

**Comment by alexge233** [comment]
Hi @john-terraspace which makefile should I use with 2.50? The `gccLinux64.mak`?

**Comment by john-terraspace** [comment]
Hi,

 

Yep, that’s the one I’m using and it works well.

**Comment by john-terraspace** [comment]
Try rename the file to just Makefile and run “make” without any arguments, that is how I have it setup on Linux, it shouldn’t make any difference but worth a shot.

**Comment by john-terraspace** [comment]
Ah.. yep that would be it 😊 I seldom re-configure my Linux VM, so I tend for forget how it’s setup until I switch it on to build Uasm !

Let me know if anything else comes up. I should have the final few commits to 2.50 done in the next few days then it should be complete and we can start looking into the whole PIC/PIE or.. “the bog of eternal stench” as I prefer to call it !

**Comment by yecril71pl** [comment]
> I hope you will pardon my ignorance here, but I have cloned the project in git, switched branches to v2.50, and pull'd. I think that went fine since I have both the files you mention above, gccLinux64.mak and gccmod.inc. When I execute
> 
> make gccLinux64.mak
> 
> I get an error:
> 
> Makefile:20: *** missing separator. Stop.
> 

    make -fgccLinux64.mak </dev/null

**Comment by john-terraspace** [comment]
Have you tried with a space?
make -f gccLinux64.mak
That normally works for me. The error looks like it's trying to use the default file.

**Comment by yecril71pl** [comment]
Well, [this](https://github.com/yecril71pl/UASM/runs/1268971201) has worked, as you can see yourself.
