### ISSUE TITLE
Master branch is broken

### ISSUE THREAD

**Issue by db4** [Terraspace/UASM#114]
I'm trying to build the last "stable" UASM from sources (version 2.49 I believe). Master branch is broken, there are unresolved conflicts is in the repo, e.g:
https://github.com/Terraspace/UASM/blob/6bf614a393e342da499a67f12ffa2516c9bb0664/tokenize.c#L959-L968

What branch/commit should I use?

**Comment by john-terraspace** [comment]
Branch 2.50 is now stable and will build. It will be up-lifted to master shortly.

**Comment by db4** [comment]
> Branch 2.50 is now stable and will build. It will be up-lifted to master shortly.

Thanks a lot. Can you also publish it (source tarball together with binaries) and all subsequent releases on https://github.com/Terraspace/UASM/releases page? It would be very convenient.

**Comment by john-terraspace** [comment]
A good idea. Will do.
