### ISSUE TITLE
-Sg option produces incorrect listing file

### ISSUE THREAD

**Issue by db4** [Terraspace/UASM#117]
Consider the following `test.asm`:
```asm
.CODE

option WIN64: 1

test_f PROC
     ret
test_f ENDP

END
```
Assemble it with `uasm -win64 -Fl -Sg test.asm` (`UASM` is built from the latest `master` branch commit). The following .lst file is created:
```
00000000                        test_f PROC
00000000  4883EC08          *   db 48h
0000                            push rbp
                                     reg rbp
000000000000004                     rbp, rsp
   00000004  4883C408           .setframe rbp, 00000008  C3                   *   .endprolog
00000005                             ret
00000005                    *   mov rsp, rbp
00000008                    *   pop rbp
00000009                    *   retn
```
This is totally wrong starting from `db 48h`. The correct code (disassembled) is:
```
test_f:
  0000000000000000: 48 83 EC 08        sub         rsp,8
  0000000000000004: 48 83 C4 08        add         rsp,8
  0000000000000008: C3                 ret
```

**Comment by john-terraspace** [comment]
Hi,

 

The 48h is a Windows ABI feature (the rex prefix) is added in the prologue to conform to other MS Compiler tools which can detect prologue based on the presence of the rex prefix. It has no effect.

 

With win64:1 RBP is being used as the stack base and there no attempt is made to optimise the prologue/epilogue. With other modes it would see there are no params and no locals and no calls so it would consider it a leaf function and optimise out the prologue/epilogue completely. The push rbp aligns the stacks so this is as expected for that mode.

**Comment by db4** [comment]
> The 48h is a Windows ABI feature (the rex prefix) is added in the prologue to conform to other MS Compiler tools which can detect prologue based on the presence of the rex prefix. It has no effect.

Yes, but listing contains neither ` sub rsp,8` nor `add rsp,8` that is actually generated. Instead, it shows
```
00000005                    *   mov rsp, rbp
00000008                    *   pop rbp
```
that are NOT generated. Why?

**Comment by john-terraspace** [comment]
I see, the listing doesn’t correspond. I will have a look.

**Comment by john-terraspace** [comment]
Found a reason for this, the listing is written on the first pass, and only on the second pass does the assembler have enough information to implement FPO. So the listing is based on the unoptimised pass 1 generated code.
