### ISSUE TITLE
elf64: incorrect code is generated for option STACKBASE:RSP

### ISSUE THREAD

**Issue by db4** [Terraspace/UASM#120]
Probably it's just not supported and should raise an error? If not, I can provide a simple test case, demonstrating the problem.

**Comment by john-terraspace** [comment]
I believe it should report an error, good spotting. (At least for now).

There may be a good reason to implement it in future?

**Comment by john-terraspace** [comment]
Done in 2.50

Please test and let me know if this now provides correct error.
