### ISSUE TITLE
qword gp to mmx register not assemblinh

### ISSUE THREAD

**Issue by john-terraspace** [Terraspace/UASM#125]
0:  48 0f 6e c0             movq   mm0,rax
4:  49 0f 6e c1             movq   mm0,r9

**Comment by mazegen** [comment]
I just wanted to report a bug when assembling MOVQ, maybe it's related to this one?

`MOVQ XMM0, EAX` should throw error but it assembles to `MOVQ MM0, EAX` instead.

**Comment by john-terraspace** [comment]
Other issue is fixed in 2.50. They were unrelated, this is fixed in 2.50 too.
