### ISSUE TITLE
MOVQ between XMM and GP register in assembled incorrectly

### ISSUE THREAD

**Issue by mazegen** [Terraspace/UASM#126]
- ~~`MOVQ RAX, XMM0` should assemble to `66480F7EC0` but UASM assembles it without the `66` prefix~~ works right with v2.49
- `MOVQ XMM0, EAX` should throw error but it assembles to `0F6EC0 MOVQ MM0, EAX` instead.

**Comment by john-terraspace** [comment]
Fixed in 2.50 now, this will error.
