### ISSUE TITLE
PROTO and PTR PROTO type comparison

### ISSUE THREAD

**Issue by vid512** [Terraspace/UASM#129]
I've just found that different prototypes of functions are considered same type, but pointers to those different prototypes are considered different types. Is this a bug, or is there some rationale behind that? Are there some clear rules about what actually is a separate type and what isn't?

Exmple:
```
.code
proto_FUNC1 typedef proto :QWORD
proto_FUNC2 typedef proto :QWORD, :QWORD
PFUNC1 typedef PTR proto_FUNC1
PFUNC2 typedef PTR proto_FUNC2
if type(proto_FUNC1) EQ type(proto_FUNC2)
  echo "PROTO types are equal"
else
  echo "PROTO types are different"
endif
if type(PFUNC1) EQ type(PFUNC2)
  echo "PTR PROTO types are equal"
else
  echo "PTR PROTO types are different"
endif
end
```
When compiled, it prints:
```
"PROTO types are equal"
"PTR PROTO types are different"
```

**Comment by john-terraspace** [comment]
I'm not 100% sure but I believe in this instance the type(PROTO) is simply "proto" so any proto will be considered equal while type(PTR PROTO) uses a different comparison that looks at what symbol type is pointed to by the PTR operator, in which case they are different. I don't think it's a bug, just the way it works(tm) :)
