### ISSUE TITLE
Add Mach-O output type

### ISSUE THREAD

**Issue by john-terraspace** [Terraspace/UASM#13]
https://developer.apple.com/library/mac/documentation/DeveloperTools/Conceptual/MachORuntime/index.html

https://www.objc.io/issues/6-build-tools/mach-o-executables/

**Comment by ldupisani** [comment]
Top link is broken.

**Comment by john-terraspace** [comment]
http://lowlevelbits.org/parsing-mach-o-files/

**Comment by john-terraspace** [comment]
Typical. Added another useful link to this section.
