### ISSUE TITLE
Handful of errors with PTR PROTO structure member

### ISSUE THREAD

**Issue by vid512** [Terraspace/UASM#132]
This code works correctly: (compile with -win64 option)
```
option casemap:none    ;needed for windows.inc

.code
code_start:

myfunc       proto :PTR
PROTO_myfunc typedef proto :PTR
PTR_myfunc   typedef ptr PROTO_myfunc

MYSTRUC struct
  myfunc PTR_myfunc ?
MYSTRUC ends

mystruc MYSTRUC <>

mov  [rbp + (mystruc.myfunc - code_start)], rcx

myfunc PROC file_name:PTR
  RET
myfunc ENDP

end
```

But if you move the **mystruc** definition behind the **myfunc** defition, you get error "Conflicting parameter definition" on definition of **myfunc**.
```
option casemap:none

.code
code_start:

myfunc       proto :PTR
PROTO_myfunc typedef proto :PTR
PTR_myfunc   typedef ptr PROTO_myfunc

MYSTRUC struct
  myfunc PTR_myfunc ?
MYSTRUC ends

mov  [rbp + (mystruc.myfunc - code_start)], rcx

myfunc PROC file_name:PTR
  RET
myfunc ENDP

mystruc MYSTRUC <>

end
```

If you move the definition of **mystruc** between MOV and defition of **myfunc**, you get the same error and then a General Failure:

```
option casemap:none

.code
code_start:

myfunc       proto :PTR
PROTO_myfunc typedef proto :PTR
PTR_myfunc   typedef ptr PROTO_myfunc

MYSTRUC struct
  myfunc PTR_myfunc ?
MYSTRUC ends

mov  [rbp + (mystruc.myfunc - code_start)], rcx

mystruc MYSTRUC <>

myfunc PROC file_name:PTR
  RET
myfunc ENDP

end
```

If you change the MOV instruction to access the structure member directly, you get one more weird error, saying "Operands must be the same size: 2 - 8" on the MOV instruction:

```
option casemap:none

.code

myfunc       proto :PTR
PROTO_myfunc typedef proto :PTR
PTR_myfunc   typedef ptr PROTO_myfunc

MYSTRUC struct
  myfunc PTR_myfunc ?
MYSTRUC ends

mov  [mystruc.myfunc], rcx

mystruc MYSTRUC <>

myfunc PROC file_name:PTR
  RET
myfunc ENDP

end
```

Something seems very wrong...

**Comment by vid512** [comment]
I have discovered this bug is not actually caused by the structure member being of PTR PROTO type, but instead by the structure member being named same as PROC.  If you change the type of member to "myfunc DQ ?" you still get all the same errors. However if you rename the structure member to something else, errors go away.

**Comment by vid512** [comment]
I vaguely remember this problem from JWASM days. It was about the WinInc structure DEBUG_EVENT having member ExitProcess, causing trouble with API function ExitProcess in some scenarios. I think it was somehow fixed at the time, but apparently the fix was not fully correct.

**Comment by VitorEAFeliciano** [comment]
`
.code

myfunc       proto :PTR
PROTO_myfunc typedef proto :PTR
PTR_myfunc   typedef ptr PROTO_myfunc

.data?
MYSTRUC struct
  myfunc PTR_myfunc ?
MYSTRUC ends

mystruc MYSTRUC <>  ;;Work's

.data
mystruct2 struct
  aa db ?
  bb dw ?
  cc dd ?
  sdd dq ?
mystruct2 ends

;align 16
;struct2 mystruct2 <>  ;;Don't work in initialized segment data. Throw General Failure

mystruct3 struct
  aa3 db ?
  bb3 dw ?
  cc3 dd ?
  sdd3 dq ?
mystruct3 ends

.data?
align 16
struct3 mystruct3 <>  ;;This works

.code

mov  [mystruc.myfunc], rcx

myfunc PROC file_name:PTR
  RET
myfunc ENDP
`

Going to see wath I can do...

**Comment by john-terraspace** [comment]
Did you guys have a resolution for this issue, perhaps we can PR it into the new 2.55 branch? - I've not tested on Linux, but the above cases and the one in https://github.com/Terraspace/UASM/issues/145 seem to work fine on Windows.

**Comment by john-terraspace** [comment]
Couldn't reproduce this issue using this test-case:

.x64
.model flat

something STRUCT
myproc dq ?
something ENDS

.code

myproc proto

mov [(type something.myproc) ptr [rax]], rax

a db 0

myproc PROC
RET
myproc ENDP

end

**Comment by vid512** [comment]
What is that test-case, and how is it relevant to the issue? All of test-cases that I have reported in both my original posts still produce same error with UASM 1.52 on Windows.

Note that, as I said in original post, the error doesn't happen always when there is a structure member named same as proc. Only sometimes, and the particular error is dependent on order of things referencing this problematic entity. I wouldn't be surprised if the error was dependent on outside OS influences, such as referencing values from uninitialized buffer etc.

**Comment by john-terraspace** [comment]
That was the code from your other issue (#145). I was curious if Vitor had any changes that fixed the issue if it was more persistent on Linux as noted above. I will continue trying some variations to see if I can get something that consistent produces the issue.

**Comment by vid512** [comment]
It wasn't the code from #145, you have added structure declaration to it, which causes the bug not to trigger. My code in first post of #145 is interesting precisely because it causes GF without the structure being declared at all, just using the symbol as if it was structure member is enough to cause GF. That might reveal some info about the nature of the bug. And yes, it still happens with UASM 2.52.

**Comment by john-terraspace** [comment]
I've fixed the cause of the general failure, that was a symbol type check using the altname field which didn't exist (null ptr).
