### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by 0xFF1E071F** [Terraspace/UASM#133]
Hello i am making linux packages for Pisi Linux
Can you tag the latest release to github releases
Thank you very much

**Comment by 0xFF1E071F** [comment]
Hello again people. Thank you for all continuing this project. When i check archlinux aur repo i saw that they pull this commit:
```
https://github.com/Terraspace/UASM.git#commit=41002d262d3a9d6ca737d72e86f6f1328d42478d
```
And release a package with version 2.50
Is this the latest one? If latest can you please tag a release as tarball package. I need this beacuse i am going to compile a package for [PisiLinux](https://pisilinux.org) distribution.
Thank you very much!

**Comment by blue-devil** [comment]
Same here
John could you please tag the latest release?

**Comment by john-terraspace** [comment]
Done for v2.55
