### ISSUE TITLE
Support to .IF/.ELSE/.ELSEIF/.ENDIF/... to x64

### ISSUE THREAD

**Issue by DebugBSD** [Terraspace/UASM#134]
I know that most of those directives are inexistent in the original MASM64 but I wonder if is it possible to add support to those directives to the UASM64 bit version. ¿Is it possible? 

Have a nice day!
Guille

**Comment by john-terraspace** [comment]
Hi, 

All the high level macros and directives from MASM32 are supported in UASM fully for 32bit, 64bit and across all target platforms (Windows, Linux and OSX).

In addition many new directives have been added to UASM such as .for .switch and the ability to use floating point comparisons with things like .if etc.. combined with the built in macro library you should have everything you could ever want!
