### ISSUE TITLE
Showing info about data structures in WinDBG 

### ISSUE THREAD

**Issue by DebugBSD** [Terraspace/UASM#140]
Hi, good morning!

I'm trying to debug a program where I've some data structures with different data types and I've found something that seems to be a bug, but I'm not sure because maybe I'm doing something wrong. 

I have the next source code:

include main.inc

Tile struct 
	x DWORD ?
	y DWORD ?
	h DWORD ?
	w DWORD ?
	m_Type DWORD ?
Tile ends

.DATA

gTiles Tile 10 DUP(<>)

.CODE

main PROC
	
mov rdi, offset gTiles
	
mov rcx, EXIT_SUCCESS
call ExitProcess
ret
main endp

end

That code builds ok (and works ok) in both MASM64 and UASM64, but the problem comes when I go into WinDBG with the version made with UASM64. That's when I get strange problems. One of them is I can't use the instruction 'dt' when debugging the source code with UASM64, meanwhile I can do that with MASM64. Next, I show you some pictures to see the problem:

(In MASM64 - OK)
![image](https://user-images.githubusercontent.com/16562480/97557780-87189700-19db-11eb-8aad-ce506b0e17af.png)

(In UASM64 - KO)
![image](https://user-images.githubusercontent.com/16562480/97557861-a31c3880-19db-11eb-9862-436a127e6b16.png)

I've read the documentation several times, and I've found the options: -Zi[0|1|2|3] which I have tried but, with no luck. I don't know if I don't understand something or maybe is a bug. 

I'm using UASM64 v2.50. 
Have a nice day!
Guille

PD: dt instruction:  `https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/dt--display-type-`

**Comment by john-terraspace** [comment]
Hi,

It might be due to WinDBG using the PDB and not Coff debugging that means the type information isn't fully compatible. I don't normally use WinDbg myself but Visual Studio. Can you try with VS and see if you have different results ? Alternatively there are other users on the forum who use WinDbg a lot and might know more about this than me.

**Comment by DebugBSD** [comment]
Hi, 

I've installed uasm64 into Visual Studio Community Edition following the instructions of the document uasm249_ext.pdf and after creating a new project based on UASM64, I have exactly the same problem. 

Anyway, it's not a eaxctly a problem because the program works as expected after building and I can still debugging using addresses instead of dt, but, some times it's quite time wasting because I have projects with thousands of data structures and it gets really stressful to debug the software using addresses.

Thank you so much for your time anyway!
Guille
