### ISSUE TITLE
Incorrect error message

### ISSUE THREAD

**Issue by gwoltman** [Terraspace/UASM#51]
Two lines of bad code follow.  The code is identical except for a unary negation operator.  The first error message is clearly incorrect.
`                      	lea	rcx, [rcx+-4*r8+64]`
`                           Error A2235: Constant value too large: FFFFFFFF00000040h`
`                        	lea	rcx, [rcx-4*r8+64]	;; Next dest pointer`
`                           Error A2065: Constant expected`

**Comment by john-terraspace** [comment]
Hi,

 

With regards to these I’ve not been able to make it assemble in anything as yet..

In both cases the scale is required to be positive (1,2,4,8) in SIB addressing.

In the first case I think the expression evaluator gets the right answer, but being negative complains that would exceed the scale values of 1,2,4 or 8.

In the second case once again SIB addressing modes can only be positive so

BASE + INDEX*SCALE + DISPLACEMENT, so the negative would through it out thinking that’s a displacement then there is a *reg straight after it.

 

Out of interest do these lines assemble anywhere for you ? I’d be curious to see what they output but I can’t imagine it’s meaningful! :)

**Comment by gwoltman** [comment]
Hi,

Yes, these lines should not assemble.  I'm sorry I did not make that
clearer.

The first error message is wrong in that hjwasm is reporting "+-r8*64"
equals the constant "FFFFFFFF00000040h".
The second error message isn't wrong, but the error "index multiplier must
be 1, 2,4, or 8" would be better.

Again, not at all a major issue.  Heck, barely even a minor issue.

Regards,
George

**Comment by john-terraspace** [comment]
Ahhh got you, I agree the error messages could be more helpful, I’ll see what we can do about it right now for 2.29, else I’ll put it on the to-do list (the never ending one ;) )
