### ISSUE TITLE
EVEX vsubsd not assembling

### ISSUE THREAD

**Issue by gwoltman** [Terraspace/UASM#53]
This code is rejected by the Uasm assembler:
vsubsd	xmm31, xmm31, xmm0
vaddsd	xmm31, xmm31, xmm0

**Comment by john-terraspace** [comment]
Will check this out asap. We’ve created some fixes/updates (part of 2.38 which will be available in the next day or so) for the other gather/scatter issues.

 

PS, have you had a chance to try the 32bit + listing stuff again ? We’ve made a lot of fixes for the 32bit build, fixed some listing specific issues as well as some memory corruption issues that might have occurred.

 

Thanks!

John

**Comment by gwoltman** [comment]
Hi John,

Thanks for the quick turnaround.

So far, I've had no issues doing Win32 builds -- even those that generate
numerous errors.  I'm upgrading a different part of my code to AVX-512.
That could be the reason I've had no problems -- or it could be you've
fixed the bug that was causing my crashes.  Let's hope its the latter.
I'll let you know if I get crashes in the future in case you'd like to
close out my win32 crash bug report.

Regards,
George

**Comment by gwoltman** [comment]
Fixed in 2.38 pre-release
