### ISSUE TITLE
Spurious "add RSP, 8" added to code

### ISSUE THREAD

**Issue by gwoltman** [Terraspace/UASM#54]
This is the code:

	TITLE   cpuidhlp
_TEXT SEGMENT
fpu_init	proc
	mov	rax, 1
	ret
fpu_init ENDP
_TEXT	ENDS
END

Compiling with HJWasm 2.30 with -c and -win64 assembles properly (same as Microsoft's ml64)
Compiling with Uasm 2.37 with -c and -win64 assembles as:

public fpu_init
_text   SEGMENT PARA 'CODE'                             ; section number 1
fpu_init PROC
        mov     rax, 1                                  ; 0000 _ 48: C7. C0, 00000001
        add     rsp, 8                                  ; 0007 _ 48: 83. C4, 08
        ret                                             ; 000B _ C3
fpu_init ENDP
_text   ENDS

**Comment by gwoltman** [comment]
I've added "OPTION PROC:NONE" to my source code.  All is well.

**Comment by john-terraspace** [comment]
I will investigate this one now. The option proc:none workaround should be ok, but with no parameters specified and no locals there should be no reason for the add rsp,8 epilogue to be generated.

**Comment by john-terraspace** [comment]
This issue is now fixed in 2.38

 

The add rsp,8 is correct, it was missing a sub rsp,8 in the prologue to ensure that RSP is always aligned 16.

**Comment by gwoltman** [comment]
Fix verified in 2.38 pre-release
