### ISSUE TITLE
vscatterqpd mis-assembly

### ISSUE THREAD

**Issue by gwoltman** [Terraspace/UASM#55]
vscatterqpd [rsi+zmm31*1+0] {k1}, zmm0

assembles as (pardon the mix of Intel and gdb syntax):

vscatterqpd %zmm0,0x0(%rsi,%zmm15,1){%k1}

**Comment by john-terraspace** [comment]
Hi,

 

We’ve tested this one in the 2.38 pre-release and it appears to be correct now.

 

John

**Comment by gwoltman** [comment]
Fixed in 2.38 pre-release
