### ISSUE TITLE
VMOV broken in 2.38 pre-release

### ISSUE THREAD

**Issue by gwoltman** [Terraspace/UASM#59]
vmovdqa64 zmm31, [r11+32]

Assembles as this (according to objconv):  

; Note: VEX prefix bits not allowed here
        vmovdqa64 zmm31, zmmword ptr [r11+20H*40H]      ; 002C _ 62 41 FD 40: 6F. 7B, 20

Note that GDB (at defuse.ca) thinks this is a valid instruction with the wrong offset:

vmovdqa64 zmm31,ZMMWORD PTR [r11+0x800]

The acid test is executing it.  Knight's Landing crashes (SIGILL) executing the above.

**Comment by john-terraspace** [comment]
Hi,

 

Please try again use: www.terraspace.co.uk/uasm.zip <http://www.terraspace.co.uk/uasm.zip> 

 

These issues should be resolved as well as error for kmov immediates.

 

Thanks!

John

**Comment by gwoltman** [comment]
Fixed in 2.38 pre-release #2
