### ISSUE TITLE
New vsubsd misassembly

### ISSUE THREAD

**Issue by gwoltman** [Terraspace/UASM#61]
in 2.38 prerelease #2, 

	vsubsd	xmm3, xmm3, xmm30

assembles as:

        vsubsd  xmm3, xmm3, xmm14                       ; 0012 _ C4 C1 63: 5C. DE

**Comment by john-terraspace** [comment]
Hi,

 

Next update is ready, please re-test:

 

www.terraspace.co.uk/uasm.zip <http://www.terraspace.co.uk/uasm.zip> 

 

Probably best to verify the existing closed issues are still solved. We’ve tested for regressions this side, but just to be safe.

 

Thanks,

John

**Comment by gwoltman** [comment]
Fixed in 2.35 prerelease #3
