### ISSUE TITLE
Include fixes/improvements from JWasm fork

### ISSUE THREAD

**Issue by XVilka** [Terraspace/UASM#62]
https://github.com/JWasm/JWasm

See also imported issues from the original sourceforge repo. Could be helpful for your fork.
Sadly we don't have time to develop it, so it would be awesome if you find something useful in it.

**Comment by XVilka** [comment]
Ah, forgot to mention, some scripts for regression testing are here https://github.com/JWasm/JWasm-regressions

**Comment by john-terraspace** [comment]
Thanks, will check it out and see if we can pull anything across that isn't already covered!
