### ISSUE TITLE
Create UASM homebrew formula

### ISSUE THREAD

**Issue by upiter** [Terraspace/UASM#63]
# Create UASM homebrew formula for macOS

## Intro
Homebrew formula let to install UASM on macOS via simple command `brew install uasm`

## Details
[Formula Cookbook](https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md)
[Acceptable Formulae](https://github.com/Homebrew/brew/blob/master/docs/Acceptable-Formulae.md)

**Comment by upiter** [comment]
Homebrew formula for UASM wasn't created, but Issue was closed without any response. Is it normal behaviour for UASM developers?

**Comment by john-terraspace** [comment]
2.47 release will be available shortly with installations for homebrew and apt-get 😊

**Comment by upiter** [comment]
Great news, @john-terraspace !
