### ISSUE TITLE
Command line broken in 2.43

### ISSUE THREAD

**Issue by gwoltman** [Terraspace/UASM#65]
Command line arguments are no longer handled properly.  A typical one for me is:

uasm32 /c /DX86_64 /DWINDOWS64 -win64 /DARCH=CORE /Foamd64\zr4_core.obj  zr4.asm

uasm complains that X86_64, ARCH, etc. are not defined.

**Comment by john-terraspace** [comment]
Hi,

 

This is fixed now. The update will be available later today.

**Comment by john-terraspace** [comment]
You can test the pre-release here:

 

www.terraspace.co.uk/uasm64.zip <http://www.terraspace.co.uk/uasm64.zip>

**Comment by john-terraspace** [comment]
2.44 is up and resolves this issue (amongst others).

 

John
