### ISSUE TITLE
VMOVSD oddity

### ISSUE THREAD

**Issue by gwoltman** [Terraspace/UASM#72]
The code
`       vmovsd  qword ptr [r11+380H], xmm0`
assembles in uasm as:
`        vmovsd  qword ptr [r11+380H], xmm0              ; 0000 _ C4 C1 FB: 11. 83, 00000380`
whereas in MASM and GCC assembles it assembles as:
`        vmovsd  qword ptr [r11+380H], xmm0              ; 0000 _ C4 C1 7B: 11. 83, 00000380`

Both versions execute (at least on Knights Landing).  However, debugging is a real pain because GDB does not recognize the UASM version.  Go to https://defuse.ca/online-x86-assembler.htm#disassembly2 and you'll see this GDB disassembly:
`0:  c4 c1 fb 11             (bad)`
`4:  83 00 00                add    DWORD PTR [rax],0x0`
`7:  03                      .byte 0x3`
`8:  80                      .byte 0x80`

Please consider changing UASM to assemble vmovsd the same way MASM and GCC does.

**Comment by john-terraspace** [comment]
Will do. We’ve done the same this side for most of the evex encodings, at one point we had a lot of different (albeit correct) encodings, but it made the automated regression testing a pain so we’re trying to standardise the encoding. I will update the packages with these fixes.

**Comment by gwoltman** [comment]
Fixed in latest test release
