### ISSUE TITLE
Incorrect code is assembling

### ISSUE THREAD

**Issue by gwoltman** [Terraspace/UASM#73]
`	vfmsub231sd xmm1, xmm2, zmm3`

assembles as

`        vfmsub231sd xmm1, xmm2, xmm3                    ; 0013 _ 62 F2 ED 08: BB. CB`

It should raise an error instead.

**Comment by john-terraspace** [comment]
Hi,

 

The others are fixed, will do this one shortly. I’m busy experimenting with that option to allow the decorator through the macro pre-parser now, hopefully can send you a test tonight with all the fixes.

 

John

**Comment by john-terraspace** [comment]
Hi,

 

Please try this test-build:

 

www.terraspace.co.uk/uasm.zip <http://www.terraspace.co.uk/uasm.zip> 

 

Includes all the encoding fixes which have been added to the regression test suite as well as a fix for the macro issue, it should allow reg {mask} through as a macro operand.

 

Cheers,

John

**Comment by gwoltman** [comment]
Fixed in latest test release
