### ISSUE TITLE
VGATHER / VSCATTER question

### ISSUE THREAD

**Issue by gwoltman** [Terraspace/UASM#81]
Intel documentation on vgather and vscatter indicates that these instructions can be called without a mask register (look at the intrinsics).  UASM insists a mask register be given.

**Comment by john-terraspace** [comment]
The documentation does seem to indicate this.. however it doesn’t work in defuse either.. So I went to review and test the C++ intrinsics as follows:

 

// ConsoleApplication3.cpp : Defines the entry point for the console application.

//

 

#include "stdafx.h"

#include <intrin.h>

 

int main()

{

       __m512i idx = _mm512_set1_epi32(1);

       

       const void *base = 0;

       _mm512_i32gather_ps(idx, base, 8);

    return 0;

}

 

 

 

       __m512i idx = _mm512_set1_epi32(1);

00C016BE  mov         eax,1  

00C016C3  vpbroadcastd zmm0,eax  

00C016C9  vmovdqu32   zmmword ptr [ebp-158h],zmm0  

00C016D3  vmovdqu32   zmm0,zmmword ptr [ebp-158h]  

00C016DD  vmovdqu32   zmmword ptr [idx],zmm0  

       

       const void *base = 0;

00C016E7  mov         dword ptr [base],0  

 

       _mm512_i32gather_ps(idx, base, 8);

00C016EE  mov         eax,dword ptr [base]  

00C016F1  vmovdqu32   zmm0,zmmword ptr [idx]  

00C016FB  kxnorw      k1,k1,k1  

00C016FF  vgatherdps  zmm1{k1},dword ptr [eax+zmm0*8]  

00C01706  vmovups     zmmword ptr [ebp-1A0h],zmm1  

 

    return 0;

00C01710  xor         eax,eax

 

It would appear the intrinsics without mask simply fill out k1 and use it anyway. I can’t find any encoding related information to avoid a mask.

**Comment by gwoltman** [comment]
Thanks.  I was hoping to eliminate many kmovw instructions.  Alas, it does not appear to be possible.
