### ISSUE TITLE
2.47 (32-bit version) raising random A2014 errors

### ISSUE THREAD

**Issue by gwoltman** [Terraspace/UASM#91]
Sorry, I cannot create a small test case.

I'm getting A2014 errors on instructions like "push r12" and "call rax".   Perhaps because zr4dwpn.obj is HUGE.  Here is the .lst file.

https://www.dropbox.com/s/y7s4aw9r5kaa64d/zr4dwpn.lst?dl=0

here is a zip file of the entire assembly source:

https://www.dropbox.com/s/0p3eryu65rfslm0/foo2.zip?dl=0

run c64.bat to assemble everything (you may want to skip directly to zr4dwpn.asm).

**Comment by john-terraspace** [comment]
Hi,

 

Verified these files assemble fine with 2.46, it’s a regression introduced by fixes to 1-byte immediate data. Will fix asap and update.

**Comment by john-terraspace** [comment]
Running through the file again I can only find A2014 errors on the following lines:

 

0025D3E1                     6      prefetcht0 [rsi+16*dist32+128]

                          Error A2014: invalid combination of opcode and operands

 

0000006E                     3      je    ??0006

                          Error A2014: invalid combination of opcode and operands

**Comment by john-terraspace** [comment]
I’ve been able to reproduce this issue, it doesn’t happen with uasm 2.46 so it’s definitely a regression.

I don’t believe it has anything to do with the file or source size as it would have affected 2.46 then.

 

I think it’s related to 1-byte displacement value fixes, what is odd is how it only occurs in this file on common/simple instructions yet the 1000 odd regression tests pass fine which most definitely use

the same instructions. Once I can narrow it down I will add specific tests for the isolated instructions.

**Comment by john-terraspace** [comment]
Hi,

I've identified the two issues that caused this and they are now fixed for UASM 2.48
However, I've run into the following line:

line 2747:
	vblendmpd zmm26 {k6}, ZMM_ONE{1to8}, zmm30 ;; 1, 1, 1, 1, 1, 1, 1		.924/.383		; 50		n 68

in zr64.mac

which is producing:
vblendmpd zmm26 {k6}, QWORD PTR [r11+48*SZPTR+576+16*SZPTR+22*8]{1to8}, zmm30

We've applied an additional fix which affects this particular instruction, the first two operands can only be registers : 

EVEX.NDS.512.66.0F38.W0 65 /r
VBLENDMPS zmm1 {k1}{z}, zmm2, zmm3/m512/m32bcst

As per the manuals.
If you can send me a fix for this I can re-test.

**Comment by gwoltman** [comment]
This bad code was reported in issue #90 along with another illegal instruction that also should raise an error.

If you'd like to test out 2.48 on the big troublesome file, simply delete the offending line from zr64.mac.

**Comment by john-terraspace** [comment]
Ah true 😊

 

Well it definitely reports an error now, I’ll just remove that line to continue the tests.

 

Thanks

**Comment by john-terraspace** [comment]
Confirmed, the solution now assembles as expected with both 32bit and 64bit with the problematic line (which reports an error now) removed.

**Comment by john-terraspace** [comment]
//  /c /DX86_64 /DWINDOWS64 -win64 /DARCH=SKX -Fl=out.lst /Foamd64\zr4dwpn_skx.obj zr4dwpn.asm
//  d:\foo2

Testing note (internal)

**Comment by gwoltman** [comment]
There are new (possibly related) problems in windows 32-bit 2.48.   

Here is the latest source:  https://www.dropbox.com/s/k726vaps952gh5h/foo3.zip?dl=0

The new error when assembling that huge zr4dwpn.asm file is:

>                            C 	zfmaddpd zmm22 {k7}{z}, zmm1, zmm24, zmm22
>                           Error A2301: {z} mask not permitted when first operand is memory

where zfmaddpd is a macro that turns 4 argument FMA instructions into Intel's 3 argument FMA instructions.  I created a small test case and it assembles just fine.

I'm going to try splitting the file in half to see if I can safely upgrade to 2.48.

**Comment by john-terraspace** [comment]
Hi,

 

That is a new error type added, it must be incorrectly triggered by the fact that it’s in a macro. 

 

Here is the current evex_macro test-cases:

 

 

KMASK equ <k3>

 

TITLE setup

OPTION EVEX:1

OPTION FLAT:1

 

zfmsubpd MACRO reg, mask, reg2, reg3, reg4

ENDM

 

.code

USE64

 

;--------------------------------------------------------

 

vsubpd zmm0 {KMASK}, zmm1, zmm2 ; direct macro substitution works.

 

;--------------------------------------------------------

 

znoconst_rounding_single_nottp MACRO zmmval, zmmcarry, kwritemask

zfmsubpd zmmcarry, {kwritemask}, zmmval, zmm24, zmm20

zfmsubpd zmm16, {kwritemask}, zmmcarry, zmm26, zmm22

vsubpd zmmval {kwritemask}, zmmval, zmm16

ENDM

 

;--------------------------------------------------------

 

znoconst MACRO zmmval, kwritemask

 

vsubpd zmmval {kwritemask}, zmmval, zmm16

    

; multiple elements can be substituted in the macro, include 

; placeholder for register and decorator.

 

vsubpd zmm2 {kwritemask}, zmmval, zmm16

 

; register + expanded decorator from macro parameter works.

 

ENDM

 

;--------------------------------------------------------

 

znoconst_rounding_single_nottp zmm3, zmm4, k6

znoconst zmm2, k1

 

;--------------------------------------------------------

; simplified example of passing a full reg + writemask

;--------------------------------------------------------

 

simplemacro2 MACRO zreg

vsubpd zreg, zmm10, zmm11

ENDM

 

simplemacro1 MACRO kwritemask

simplemacro2 zmm16 {kwritemask}

ENDM

 

simplemacro1 k6

 

;As proof that passing "zmm16 {k6}" as one argument to a macro is valid,

;consider that the following does work:

 

simplemacro3 MACRO zreg, kwritemask

simplemacro2 zreg {kwritemask}

ENDM

 

simplemacro3 zmm16, k6

 

;The above should expand to the valid "vsubpd zmm16 {k6}, zmm10, zmm11"

 

 

Could you give the relevant sample portion to add into the test and I’ll get it fixed today.

Thanks

John

**Comment by john-terraspace** [comment]
I assume also that it should raise this same error when using uasm64 ?

 

The random errors were fixed – it was due to the evex indicator not resetting properly in some cases during pre-parsing if it bailed out early so I would think this is different.

**Comment by gwoltman** [comment]
Good news:  I was able to create a small test case.   Add this to any asm code and you'll get an error.   This works in 2.46

`FOOBAR MACRO`
`	zfmsubpd zmm15 {k7}{z}, zmm15, zmm27, zmm11`
`ENDM`

**Comment by john-terraspace** [comment]
Hi, yep I’ve just done the same, I already had that specific type of macro in my regression tests, it just didn’t have a case with {z} in it, fixing it now 😊

**Comment by john-terraspace** [comment]
Hi,

 

Issue has been fixed. 2.48b branch updated and new binary packages on the site.

 

Result from testing your latest file:

 

D:\foo2>c:\jwasm\uasm32 /c /DX86_64 /DWINDOWS64 -win64 /DARCH=SKX -Fl=out.lst /Foamd64\zr4dwpn_skx.obj zr4dwpn.asm

UASM v2.48, Feb 15 2019, Masm-compatible assembler.

Portions Copyright (c) 1992-2002 Sybase, Inc. All Rights Reserved.

Source code is available under the Sybase Open Watcom Public License.

 

zr4dwpn.asm: 136 lines, 9 passes, 35354 ms, 0 warnings, 0 errors

**Comment by gwoltman** [comment]
All fixed.  Thanks!
