### ISSUE TITLE
vpmovzxbq not assembling

### ISSUE THREAD

**Issue by gwoltman** [Terraspace/UASM#92]
These two valid instructions are not assembling:

	vpmovzxbq zmm31, xmm0			
	vpmovzxbq zmm31, QWORD PTR [r11]

**Comment by john-terraspace** [comment]
Added to the current fixes, we should have an update in the next few days with all of these addressed.

**Comment by john-terraspace** [comment]
Fixed in v2.48 along with other evex related issues. Please re test.

**Comment by gwoltman** [comment]
The v2.48 zip files linked to on http://www.terraspace.co.uk/uasm.html contain UASM v2.47

**Comment by gwoltman** [comment]
Correction:  The URL is incorrect.  I typed in the correct URL and have version 2.48, testing now.

**Comment by gwoltman** [comment]
Fixed in 2.48
