### ISSUE TITLE
vfmadd132sd not assembling properly

### ISSUE THREAD

**Issue by gwoltman** [Terraspace/UASM#96]
In 2.48
	`vfmadd132sd xmm1, xmm30, [r11]`
assembles as
	`vfmadd132sd xmm1, xmm14, [r11]`

**Comment by john-terraspace** [comment]
Hi,

 

Will fix shortly. I don’t think this justifies a 2.49 release on it’s own, so I’ll do a 2.48.2 patch.

 

Now that we have a totally new code-gen in place as we identify these problem instructions I will migrate them from the old code-gen to the new one.

 

John

**Comment by john-terraspace** [comment]
Hi,

Packages updated (17/2/2019) Please try again.

**Comment by gwoltman** [comment]
Fixed.   Five minutes into a long QA run with no errors thusfar.

**Comment by john-terraspace** [comment]
Excellent, keep me posted on the progress. If there are any other quick fixes we can get applied to 2.48 still that won’t be an issue.

 

John
