### ISSUE TITLE
fxch not assembling properly

### ISSUE THREAD

**Issue by gwoltman** [Terraspace/UASM#98]
In 2.48

`	fxch st(2)`

assembles as

`	fxch st(1)`

**Comment by john-terraspace** [comment]
Hi,

 

I wasn’t able to re-create this issue, the regression test case we have is:

 

 

option flat:1

 

.code

 

                use32

                

                fxch

                fxch st(1)

                fxch st(3)

                fxch st(7)

                fxch st(2)

                fxch st(0)

 

.data

                

Which produces :

 

0:  d9 c9                   fxch   st(1)
2:  d9 c9                   fxch   st(1)
4:  d9 cb                   fxch   st(3)
6:  d9 cf                   fxch   st(7)
8:  d9 ca                   fxch   st(2)
a:  d9 c8                   fxch   st(0)

 

In any event, I’ve made sure that the new code-gen definitely only handles FXCH (with no operands) all other forms go back to the old code-gen for now. I’ve updated git as well as the packages on the site dated 20th Feb. Please try again.

 

John

**Comment by gwoltman** [comment]
Hi,

Strange.  My test case was very simple:


TITLE   setup

OPTION EVEX:1

_TEXT SEGMENT

XYZ PROC

fxch st(2)

ret
XYZ ENDP

_TEXT ENDS
END

which produced this according to Agner Fog's disassembler:

; Disassembly of file: foo.obj
; Wed Feb 20 09:44:59 2019
; Mode: 64 bits
; Syntax: MASM/ML64
; Instruction set: 8086, x64, 80x87

public XYZ


_text   SEGMENT PARA 'CODE'                             ; section number 1

XYZ     PROC
        fxch    st(1)                                   ; 0000 _ D9. C9
        ret                                             ; 0002 _ C3
XYZ     ENDP

_text   ENDS

_data   SEGMENT PARA 'DATA'                             ; section number 2

_data   ENDS

END


I'm downloading the new version now.

**Comment by gwoltman** [comment]
Patched version of 2.48 now works.   Thanks.

**Comment by john-terraspace** [comment]
Great. 

 

The only thing I can think is that it might have been a machine specific issue, due to the new code-gen only handling fxch without operands yet, versions with opnds fall back to the old code-gen. However the opnd-matching didn’t have ST(n) yet, so it’s “possible” that some stray value caused a false-match. Now the ST(n)’s are fully matched in the new code-gen too.
