### ISSUE TITLE
cmp qword ptr [64bitregister], "string"

### ISSUE THREAD

**Issue by exit2** [Terraspace/UASM#99]
If I use instruction like:
cmp qword ptr [rax], "12345678"
UASM doesn't compile it. I think it is correct, because such instruction doesn't exists.

cmp qword ptr [rax], "1234" 
UASM compile this instruction. But I think it will be better if compiler display warning (not error). Because I think if someone using such instruction it is 99% mistake and warning will be great.
I am talking about use with string.

**Comment by john-terraspace** [comment]
Hi,

 

Agreed, the string is basically converted into a 32bit number, in the 2nd case I assume the immediate value is small enough to be sign extended to allow the cmp. In the first the value must too great,

Not sure off-hand what “12345678” turns to .. but it would make sense to have a warning if the immediate data is too large.

**Comment by john-terraspace** [comment]
Immediate data being too large will generate an error, warning for valid sized conversion of string immediate data is going to cause some come backs with a lot of legacy code that does this already and doesn't show any warnings, so at the moment I'm not too inclined to change the behaviour.
